"""Add giver_claim_message_id and giver_claim_chat_id for Phase 4

Revision ID: afcb6cc74ab8
Revises: 4f5f3043495c
Create Date: 2026-08-04 08:25:10.706090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcb6cc74ab8'
down_revision: Union[str, Sequence[str], None] = '4f5f3043495c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promises', sa.Column('giver_claim_message_id', sa.Integer(), nullable=True))
    op.add_column('promises', sa.Column('giver_claim_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promises', 'giver_claim_chat_id')
    op.drop_column('promises', 'giver_claim_message_id')
    # ### end Alembic commands ###
